/* This file is automatically generated. Edits will be lost.*/
<<<<<<< HEAD
const int buildversion = 4;
=======
const int buildversion = 1;
>>>>>>> 50ea8444a9a5c46d80696dbd43800fc5df0d015f
const char buildconfig[] = "DUMBVM";
